export default {
  "login": "KrakenLynch",
  "id": 52416932,
  "node_id": "MDQ6VXNlcjUyNDE2OTMy",
  "avatar_url": "https://avatars.githubusercontent.com/u/52416932?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/KrakenLynch",
  "html_url": "https://github.com/KrakenLynch",
  "followers_url": "https://api.github.com/users/KrakenLynch/followers",
  "following_url": "https://api.github.com/users/KrakenLynch/following{/other_user}",
  "gists_url": "https://api.github.com/users/KrakenLynch/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/KrakenLynch/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/KrakenLynch/subscriptions",
  "organizations_url": "https://api.github.com/users/KrakenLynch/orgs",
  "repos_url": "https://api.github.com/users/KrakenLynch/repos",
  "events_url": "https://api.github.com/users/KrakenLynch/events{/privacy}",
  "received_events_url": "https://api.github.com/users/KrakenLynch/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Danish Sayed",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 1,
  "public_gists": 0,
  "followers": 2,
  "following": 4,
  "created_at": "2019-07-01T14:28:27Z",
  "updated_at": "2021-01-30T09:24:17Z"
  }